#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
xrandr --output edp-1 --mode 1920x1080  &

 picom &
 /usr/libexec/polkit-gnome-authentication-agent-1 &
feh --bg-scale /home/alex/wallpapers/clay-banks-u27Rrbs9Dwc-unsplash.jpg
nm-applet &
udiskie & 
xsetroot -cursor_name left_ptr 
bspc monitor -d . . . . . . . . . .

bspc config border_width         2
bspc config window_gap           22
bspc config focused_border_color "#ffffff"
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
